/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package signfakes

import (
	"sync"

	"sigs.k8s.io/release-sdk/sign"
)

type FakeImpl struct {
	VerifyInternalStub        func(*sign.Signer, string) (*sign.SignedObject, error)
	verifyInternalMutex       sync.RWMutex
	verifyInternalArgsForCall []struct {
		arg1 *sign.Signer
		arg2 string
	}
	verifyInternalReturns struct {
		result1 *sign.SignedObject
		result2 error
	}
	verifyInternalReturnsOnCall map[int]struct {
		result1 *sign.SignedObject
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImpl) VerifyInternal(arg1 *sign.Signer, arg2 string) (*sign.SignedObject, error) {
	fake.verifyInternalMutex.Lock()
	ret, specificReturn := fake.verifyInternalReturnsOnCall[len(fake.verifyInternalArgsForCall)]
	fake.verifyInternalArgsForCall = append(fake.verifyInternalArgsForCall, struct {
		arg1 *sign.Signer
		arg2 string
	}{arg1, arg2})
	stub := fake.VerifyInternalStub
	fakeReturns := fake.verifyInternalReturns
	fake.recordInvocation("VerifyInternal", []interface{}{arg1, arg2})
	fake.verifyInternalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) VerifyInternalCallCount() int {
	fake.verifyInternalMutex.RLock()
	defer fake.verifyInternalMutex.RUnlock()
	return len(fake.verifyInternalArgsForCall)
}

func (fake *FakeImpl) VerifyInternalCalls(stub func(*sign.Signer, string) (*sign.SignedObject, error)) {
	fake.verifyInternalMutex.Lock()
	defer fake.verifyInternalMutex.Unlock()
	fake.VerifyInternalStub = stub
}

func (fake *FakeImpl) VerifyInternalArgsForCall(i int) (*sign.Signer, string) {
	fake.verifyInternalMutex.RLock()
	defer fake.verifyInternalMutex.RUnlock()
	argsForCall := fake.verifyInternalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImpl) VerifyInternalReturns(result1 *sign.SignedObject, result2 error) {
	fake.verifyInternalMutex.Lock()
	defer fake.verifyInternalMutex.Unlock()
	fake.VerifyInternalStub = nil
	fake.verifyInternalReturns = struct {
		result1 *sign.SignedObject
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) VerifyInternalReturnsOnCall(i int, result1 *sign.SignedObject, result2 error) {
	fake.verifyInternalMutex.Lock()
	defer fake.verifyInternalMutex.Unlock()
	fake.VerifyInternalStub = nil
	if fake.verifyInternalReturnsOnCall == nil {
		fake.verifyInternalReturnsOnCall = make(map[int]struct {
			result1 *sign.SignedObject
			result2 error
		})
	}
	fake.verifyInternalReturnsOnCall[i] = struct {
		result1 *sign.SignedObject
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.verifyInternalMutex.RLock()
	defer fake.verifyInternalMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImpl) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
