/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package signfakes

import (
	"context"
	"net/http"
	"sync"

	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/google/go-containerregistry/pkg/crane"
	"github.com/google/go-containerregistry/pkg/name"
	"github.com/sirupsen/logrus"
	"sigs.k8s.io/release-sdk/sign"
)

type FakeImpl struct {
	DigestStub        func(string, ...crane.Option) (string, error)
	digestMutex       sync.RWMutex
	digestArgsForCall []FakeImplDigestArgs
	digestReturns     struct {
		result1 string
		result2 error
	}
	digestReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FileExistsStub        func(string) bool
	fileExistsMutex       sync.RWMutex
	fileExistsArgsForCall []FakeImplFileExistsArgs
	fileExistsReturns     struct {
		result1 bool
	}
	fileExistsReturnsOnCall map[int]struct {
		result1 bool
	}
	ImagesSignedStub        func(context.Context, *sign.Signer, ...string) (*sync.Map, error)
	imagesSignedMutex       sync.RWMutex
	imagesSignedArgsForCall []FakeImplImagesSignedArgs
	imagesSignedReturns     struct {
		result1 *sync.Map
		result2 error
	}
	imagesSignedReturnsOnCall map[int]struct {
		result1 *sync.Map
		result2 error
	}
	NewWithContextStub        func(context.Context, name.Registry, authn.Authenticator, http.RoundTripper, []string) (http.RoundTripper, error)
	newWithContextMutex       sync.RWMutex
	newWithContextArgsForCall []FakeImplNewWithContextArgs
	newWithContextReturns     struct {
		result1 http.RoundTripper
		result2 error
	}
	newWithContextReturnsOnCall map[int]struct {
		result1 http.RoundTripper
		result2 error
	}
	ParseReferenceStub        func(string, ...name.Option) (name.Reference, error)
	parseReferenceMutex       sync.RWMutex
	parseReferenceArgsForCall []FakeImplParseReferenceArgs
	parseReferenceReturns     struct {
		result1 name.Reference
		result2 error
	}
	parseReferenceReturnsOnCall map[int]struct {
		result1 name.Reference
		result2 error
	}
	SignFileInternalStub        func(context.Context, *sign.Options, string, string) error
	signFileInternalMutex       sync.RWMutex
	signFileInternalArgsForCall []FakeImplSignFileInternalArgs
	signFileInternalReturns     struct {
		result1 error
	}
	signFileInternalReturnsOnCall map[int]struct {
		result1 error
	}
	SignImageInternalStub        func(context.Context, *sign.Options, string, string) error
	signImageInternalMutex       sync.RWMutex
	signImageInternalArgsForCall []FakeImplSignImageInternalArgs
	signImageInternalReturns     struct {
		result1 error
	}
	signImageInternalReturnsOnCall map[int]struct {
		result1 error
	}
	TlogEntryUUIDsStub        func(context.Context, *sign.Options, string) ([]string, error)
	tlogEntryUUIDsMutex       sync.RWMutex
	tlogEntryUUIDsArgsForCall []FakeImplTlogEntryUUIDsArgs
	tlogEntryUUIDsReturns     struct {
		result1 []string
		result2 error
	}
	tlogEntryUUIDsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	TokenFromProvidersStub        func(context.Context, *logrus.Logger) (string, error)
	tokenFromProvidersMutex       sync.RWMutex
	tokenFromProvidersArgsForCall []FakeImplTokenFromProvidersArgs
	tokenFromProvidersReturns     struct {
		result1 string
		result2 error
	}
	tokenFromProvidersReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	VerifyFileInternalStub        func(context.Context, *sign.Options, string, bool) error
	verifyFileInternalMutex       sync.RWMutex
	verifyFileInternalArgsForCall []FakeImplVerifyFileInternalArgs
	verifyFileInternalReturns     struct {
		result1 error
	}
	verifyFileInternalReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyImageInternalStub        func(context.Context, *sign.Options, string) (string, error)
	verifyImageInternalMutex       sync.RWMutex
	verifyImageInternalArgsForCall []FakeImplVerifyImageInternalArgs
	verifyImageInternalReturns     struct {
		result1 string
		result2 error
	}
	verifyImageInternalReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeImplDigestArgs holds the arguments of one call to Digest.
type FakeImplDigestArgs struct {
	Arg1 string
	Arg2 []crane.Option
}

// FakeImplFileExistsArgs holds the arguments of one call to FileExists.
type FakeImplFileExistsArgs struct {
	Arg1 string
}

// FakeImplImagesSignedArgs holds the arguments of one call to ImagesSigned.
type FakeImplImagesSignedArgs struct {
	Arg1 context.Context
	Arg2 *sign.Signer
	Arg3 []string
}

// FakeImplNewWithContextArgs holds the arguments of one call to NewWithContext.
type FakeImplNewWithContextArgs struct {
	Arg1 context.Context
	Arg2 name.Registry
	Arg3 authn.Authenticator
	Arg4 http.RoundTripper
	Arg5 []string
}

// FakeImplParseReferenceArgs holds the arguments of one call to ParseReference.
type FakeImplParseReferenceArgs struct {
	Arg1 string
	Arg2 []name.Option
}

// FakeImplSignFileInternalArgs holds the arguments of one call to SignFileInternal.
type FakeImplSignFileInternalArgs struct {
	Arg1 context.Context
	Arg2 *sign.Options
	Arg3 string
	Arg4 string
}

// FakeImplSignImageInternalArgs holds the arguments of one call to SignImageInternal.
type FakeImplSignImageInternalArgs struct {
	Arg1 context.Context
	Arg2 *sign.Options
	Arg3 string
	Arg4 string
}

// FakeImplTlogEntryUUIDsArgs holds the arguments of one call to TlogEntryUUIDs.
type FakeImplTlogEntryUUIDsArgs struct {
	Arg1 context.Context
	Arg2 *sign.Options
	Arg3 string
}

// FakeImplTokenFromProvidersArgs holds the arguments of one call to TokenFromProviders.
type FakeImplTokenFromProvidersArgs struct {
	Arg1 context.Context
	Arg2 *logrus.Logger
}

// FakeImplVerifyFileInternalArgs holds the arguments of one call to VerifyFileInternal.
type FakeImplVerifyFileInternalArgs struct {
	Arg1 context.Context
	Arg2 *sign.Options
	Arg3 string
	Arg4 bool
}

// FakeImplVerifyImageInternalArgs holds the arguments of one call to VerifyImageInternal.
type FakeImplVerifyImageInternalArgs struct {
	Arg1 context.Context
	Arg2 *sign.Options
	Arg3 string
}

func (fake *FakeImpl) Digest(arg1 string, arg2 ...crane.Option) (string, error) {
	var arg2Copy []crane.Option
	if arg2 != nil {
		arg2Copy = make([]crane.Option, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.digestMutex.Lock()
	ret, specificReturn := fake.digestReturnsOnCall[len(fake.digestArgsForCall)]
	fake.digestArgsForCall = append(fake.digestArgsForCall, FakeImplDigestArgs{arg1, arg2Copy})
	stub := fake.DigestStub
	fakeReturns := fake.digestReturns
	fake.recordInvocation("Digest", []interface{}{arg1, arg2Copy})
	fake.digestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) DigestCallCount() int {
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	return len(fake.digestArgsForCall)
}

func (fake *FakeImpl) DigestCalls(stub func(string, ...crane.Option) (string, error)) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = stub
}

func (fake *FakeImpl) DigestArgsForCall(i int) (string, []crane.Option) {
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	argsForCall := fake.digestArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) DigestArgs() []FakeImplDigestArgs {
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	args := make([]FakeImplDigestArgs, len(fake.digestArgsForCall))
	copy(args, fake.digestArgsForCall)
	return args
}

func (fake *FakeImpl) DigestReturns(result1 string, result2 error) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	fake.digestReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) DigestReturnsOnCall(i int, result1 string, result2 error) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	if fake.digestReturnsOnCall == nil {
		fake.digestReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.digestReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) FileExists(arg1 string) bool {
	fake.fileExistsMutex.Lock()
	ret, specificReturn := fake.fileExistsReturnsOnCall[len(fake.fileExistsArgsForCall)]
	fake.fileExistsArgsForCall = append(fake.fileExistsArgsForCall, FakeImplFileExistsArgs{arg1})
	stub := fake.FileExistsStub
	fakeReturns := fake.fileExistsReturns
	fake.recordInvocation("FileExists", []interface{}{arg1})
	fake.fileExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) FileExistsCallCount() int {
	fake.fileExistsMutex.RLock()
	defer fake.fileExistsMutex.RUnlock()
	return len(fake.fileExistsArgsForCall)
}

func (fake *FakeImpl) FileExistsCalls(stub func(string) bool) {
	fake.fileExistsMutex.Lock()
	defer fake.fileExistsMutex.Unlock()
	fake.FileExistsStub = stub
}

func (fake *FakeImpl) FileExistsArgsForCall(i int) string {
	fake.fileExistsMutex.RLock()
	defer fake.fileExistsMutex.RUnlock()
	argsForCall := fake.fileExistsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakeImpl) FileExistsArgs() []FakeImplFileExistsArgs {
	fake.fileExistsMutex.RLock()
	defer fake.fileExistsMutex.RUnlock()
	args := make([]FakeImplFileExistsArgs, len(fake.fileExistsArgsForCall))
	copy(args, fake.fileExistsArgsForCall)
	return args
}

func (fake *FakeImpl) FileExistsReturns(result1 bool) {
	fake.fileExistsMutex.Lock()
	defer fake.fileExistsMutex.Unlock()
	fake.FileExistsStub = nil
	fake.fileExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeImpl) FileExistsReturnsOnCall(i int, result1 bool) {
	fake.fileExistsMutex.Lock()
	defer fake.fileExistsMutex.Unlock()
	fake.FileExistsStub = nil
	if fake.fileExistsReturnsOnCall == nil {
		fake.fileExistsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.fileExistsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeImpl) ImagesSigned(arg1 context.Context, arg2 *sign.Signer, arg3 ...string) (*sync.Map, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.imagesSignedMutex.Lock()
	ret, specificReturn := fake.imagesSignedReturnsOnCall[len(fake.imagesSignedArgsForCall)]
	fake.imagesSignedArgsForCall = append(fake.imagesSignedArgsForCall, FakeImplImagesSignedArgs{arg1, arg2, arg3Copy})
	stub := fake.ImagesSignedStub
	fakeReturns := fake.imagesSignedReturns
	fake.recordInvocation("ImagesSigned", []interface{}{arg1, arg2, arg3Copy})
	fake.imagesSignedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ImagesSignedCallCount() int {
	fake.imagesSignedMutex.RLock()
	defer fake.imagesSignedMutex.RUnlock()
	return len(fake.imagesSignedArgsForCall)
}

func (fake *FakeImpl) ImagesSignedCalls(stub func(context.Context, *sign.Signer, ...string) (*sync.Map, error)) {
	fake.imagesSignedMutex.Lock()
	defer fake.imagesSignedMutex.Unlock()
	fake.ImagesSignedStub = stub
}

func (fake *FakeImpl) ImagesSignedArgsForCall(i int) (context.Context, *sign.Signer, []string) {
	fake.imagesSignedMutex.RLock()
	defer fake.imagesSignedMutex.RUnlock()
	argsForCall := fake.imagesSignedArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) ImagesSignedArgs() []FakeImplImagesSignedArgs {
	fake.imagesSignedMutex.RLock()
	defer fake.imagesSignedMutex.RUnlock()
	args := make([]FakeImplImagesSignedArgs, len(fake.imagesSignedArgsForCall))
	copy(args, fake.imagesSignedArgsForCall)
	return args
}

func (fake *FakeImpl) ImagesSignedReturns(result1 *sync.Map, result2 error) {
	fake.imagesSignedMutex.Lock()
	defer fake.imagesSignedMutex.Unlock()
	fake.ImagesSignedStub = nil
	fake.imagesSignedReturns = struct {
		result1 *sync.Map
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ImagesSignedReturnsOnCall(i int, result1 *sync.Map, result2 error) {
	fake.imagesSignedMutex.Lock()
	defer fake.imagesSignedMutex.Unlock()
	fake.ImagesSignedStub = nil
	if fake.imagesSignedReturnsOnCall == nil {
		fake.imagesSignedReturnsOnCall = make(map[int]struct {
			result1 *sync.Map
			result2 error
		})
	}
	fake.imagesSignedReturnsOnCall[i] = struct {
		result1 *sync.Map
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewWithContext(arg1 context.Context, arg2 name.Registry, arg3 authn.Authenticator, arg4 http.RoundTripper, arg5 []string) (http.RoundTripper, error) {
	var arg5Copy []string
	if arg5 != nil {
		arg5Copy = make([]string, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.newWithContextMutex.Lock()
	ret, specificReturn := fake.newWithContextReturnsOnCall[len(fake.newWithContextArgsForCall)]
	fake.newWithContextArgsForCall = append(fake.newWithContextArgsForCall, FakeImplNewWithContextArgs{arg1, arg2, arg3, arg4, arg5Copy})
	stub := fake.NewWithContextStub
	fakeReturns := fake.newWithContextReturns
	fake.recordInvocation("NewWithContext", []interface{}{arg1, arg2, arg3, arg4, arg5Copy})
	fake.newWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) NewWithContextCallCount() int {
	fake.newWithContextMutex.RLock()
	defer fake.newWithContextMutex.RUnlock()
	return len(fake.newWithContextArgsForCall)
}

func (fake *FakeImpl) NewWithContextCalls(stub func(context.Context, name.Registry, authn.Authenticator, http.RoundTripper, []string) (http.RoundTripper, error)) {
	fake.newWithContextMutex.Lock()
	defer fake.newWithContextMutex.Unlock()
	fake.NewWithContextStub = stub
}

func (fake *FakeImpl) NewWithContextArgsForCall(i int) (context.Context, name.Registry, authn.Authenticator, http.RoundTripper, []string) {
	fake.newWithContextMutex.RLock()
	defer fake.newWithContextMutex.RUnlock()
	argsForCall := fake.newWithContextArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeImpl) NewWithContextArgs() []FakeImplNewWithContextArgs {
	fake.newWithContextMutex.RLock()
	defer fake.newWithContextMutex.RUnlock()
	args := make([]FakeImplNewWithContextArgs, len(fake.newWithContextArgsForCall))
	copy(args, fake.newWithContextArgsForCall)
	return args
}

func (fake *FakeImpl) NewWithContextReturns(result1 http.RoundTripper, result2 error) {
	fake.newWithContextMutex.Lock()
	defer fake.newWithContextMutex.Unlock()
	fake.NewWithContextStub = nil
	fake.newWithContextReturns = struct {
		result1 http.RoundTripper
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) NewWithContextReturnsOnCall(i int, result1 http.RoundTripper, result2 error) {
	fake.newWithContextMutex.Lock()
	defer fake.newWithContextMutex.Unlock()
	fake.NewWithContextStub = nil
	if fake.newWithContextReturnsOnCall == nil {
		fake.newWithContextReturnsOnCall = make(map[int]struct {
			result1 http.RoundTripper
			result2 error
		})
	}
	fake.newWithContextReturnsOnCall[i] = struct {
		result1 http.RoundTripper
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ParseReference(arg1 string, arg2 ...name.Option) (name.Reference, error) {
	var arg2Copy []name.Option
	if arg2 != nil {
		arg2Copy = make([]name.Option, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.parseReferenceMutex.Lock()
	ret, specificReturn := fake.parseReferenceReturnsOnCall[len(fake.parseReferenceArgsForCall)]
	fake.parseReferenceArgsForCall = append(fake.parseReferenceArgsForCall, FakeImplParseReferenceArgs{arg1, arg2Copy})
	stub := fake.ParseReferenceStub
	fakeReturns := fake.parseReferenceReturns
	fake.recordInvocation("ParseReference", []interface{}{arg1, arg2Copy})
	fake.parseReferenceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) ParseReferenceCallCount() int {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	return len(fake.parseReferenceArgsForCall)
}

func (fake *FakeImpl) ParseReferenceCalls(stub func(string, ...name.Option) (name.Reference, error)) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = stub
}

func (fake *FakeImpl) ParseReferenceArgsForCall(i int) (string, []name.Option) {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	argsForCall := fake.parseReferenceArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) ParseReferenceArgs() []FakeImplParseReferenceArgs {
	fake.parseReferenceMutex.RLock()
	defer fake.parseReferenceMutex.RUnlock()
	args := make([]FakeImplParseReferenceArgs, len(fake.parseReferenceArgsForCall))
	copy(args, fake.parseReferenceArgsForCall)
	return args
}

func (fake *FakeImpl) ParseReferenceReturns(result1 name.Reference, result2 error) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = nil
	fake.parseReferenceReturns = struct {
		result1 name.Reference
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) ParseReferenceReturnsOnCall(i int, result1 name.Reference, result2 error) {
	fake.parseReferenceMutex.Lock()
	defer fake.parseReferenceMutex.Unlock()
	fake.ParseReferenceStub = nil
	if fake.parseReferenceReturnsOnCall == nil {
		fake.parseReferenceReturnsOnCall = make(map[int]struct {
			result1 name.Reference
			result2 error
		})
	}
	fake.parseReferenceReturnsOnCall[i] = struct {
		result1 name.Reference
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) SignFileInternal(arg1 context.Context, arg2 *sign.Options, arg3 string, arg4 string) error {
	fake.signFileInternalMutex.Lock()
	ret, specificReturn := fake.signFileInternalReturnsOnCall[len(fake.signFileInternalArgsForCall)]
	fake.signFileInternalArgsForCall = append(fake.signFileInternalArgsForCall, FakeImplSignFileInternalArgs{arg1, arg2, arg3, arg4})
	stub := fake.SignFileInternalStub
	fakeReturns := fake.signFileInternalReturns
	fake.recordInvocation("SignFileInternal", []interface{}{arg1, arg2, arg3, arg4})
	fake.signFileInternalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) SignFileInternalCallCount() int {
	fake.signFileInternalMutex.RLock()
	defer fake.signFileInternalMutex.RUnlock()
	return len(fake.signFileInternalArgsForCall)
}

func (fake *FakeImpl) SignFileInternalCalls(stub func(context.Context, *sign.Options, string, string) error) {
	fake.signFileInternalMutex.Lock()
	defer fake.signFileInternalMutex.Unlock()
	fake.SignFileInternalStub = stub
}

func (fake *FakeImpl) SignFileInternalArgsForCall(i int) (context.Context, *sign.Options, string, string) {
	fake.signFileInternalMutex.RLock()
	defer fake.signFileInternalMutex.RUnlock()
	argsForCall := fake.signFileInternalArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) SignFileInternalArgs() []FakeImplSignFileInternalArgs {
	fake.signFileInternalMutex.RLock()
	defer fake.signFileInternalMutex.RUnlock()
	args := make([]FakeImplSignFileInternalArgs, len(fake.signFileInternalArgsForCall))
	copy(args, fake.signFileInternalArgsForCall)
	return args
}

func (fake *FakeImpl) SignFileInternalReturns(result1 error) {
	fake.signFileInternalMutex.Lock()
	defer fake.signFileInternalMutex.Unlock()
	fake.SignFileInternalStub = nil
	fake.signFileInternalReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) SignFileInternalReturnsOnCall(i int, result1 error) {
	fake.signFileInternalMutex.Lock()
	defer fake.signFileInternalMutex.Unlock()
	fake.SignFileInternalStub = nil
	if fake.signFileInternalReturnsOnCall == nil {
		fake.signFileInternalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.signFileInternalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) SignImageInternal(arg1 context.Context, arg2 *sign.Options, arg3 string, arg4 string) error {
	fake.signImageInternalMutex.Lock()
	ret, specificReturn := fake.signImageInternalReturnsOnCall[len(fake.signImageInternalArgsForCall)]
	fake.signImageInternalArgsForCall = append(fake.signImageInternalArgsForCall, FakeImplSignImageInternalArgs{arg1, arg2, arg3, arg4})
	stub := fake.SignImageInternalStub
	fakeReturns := fake.signImageInternalReturns
	fake.recordInvocation("SignImageInternal", []interface{}{arg1, arg2, arg3, arg4})
	fake.signImageInternalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) SignImageInternalCallCount() int {
	fake.signImageInternalMutex.RLock()
	defer fake.signImageInternalMutex.RUnlock()
	return len(fake.signImageInternalArgsForCall)
}

func (fake *FakeImpl) SignImageInternalCalls(stub func(context.Context, *sign.Options, string, string) error) {
	fake.signImageInternalMutex.Lock()
	defer fake.signImageInternalMutex.Unlock()
	fake.SignImageInternalStub = stub
}

func (fake *FakeImpl) SignImageInternalArgsForCall(i int) (context.Context, *sign.Options, string, string) {
	fake.signImageInternalMutex.RLock()
	defer fake.signImageInternalMutex.RUnlock()
	argsForCall := fake.signImageInternalArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) SignImageInternalArgs() []FakeImplSignImageInternalArgs {
	fake.signImageInternalMutex.RLock()
	defer fake.signImageInternalMutex.RUnlock()
	args := make([]FakeImplSignImageInternalArgs, len(fake.signImageInternalArgsForCall))
	copy(args, fake.signImageInternalArgsForCall)
	return args
}

func (fake *FakeImpl) SignImageInternalReturns(result1 error) {
	fake.signImageInternalMutex.Lock()
	defer fake.signImageInternalMutex.Unlock()
	fake.SignImageInternalStub = nil
	fake.signImageInternalReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) SignImageInternalReturnsOnCall(i int, result1 error) {
	fake.signImageInternalMutex.Lock()
	defer fake.signImageInternalMutex.Unlock()
	fake.SignImageInternalStub = nil
	if fake.signImageInternalReturnsOnCall == nil {
		fake.signImageInternalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.signImageInternalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) TlogEntryUUIDs(arg1 context.Context, arg2 *sign.Options, arg3 string) ([]string, error) {
	fake.tlogEntryUUIDsMutex.Lock()
	ret, specificReturn := fake.tlogEntryUUIDsReturnsOnCall[len(fake.tlogEntryUUIDsArgsForCall)]
	fake.tlogEntryUUIDsArgsForCall = append(fake.tlogEntryUUIDsArgsForCall, FakeImplTlogEntryUUIDsArgs{arg1, arg2, arg3})
	stub := fake.TlogEntryUUIDsStub
	fakeReturns := fake.tlogEntryUUIDsReturns
	fake.recordInvocation("TlogEntryUUIDs", []interface{}{arg1, arg2, arg3})
	fake.tlogEntryUUIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) TlogEntryUUIDsCallCount() int {
	fake.tlogEntryUUIDsMutex.RLock()
	defer fake.tlogEntryUUIDsMutex.RUnlock()
	return len(fake.tlogEntryUUIDsArgsForCall)
}

func (fake *FakeImpl) TlogEntryUUIDsCalls(stub func(context.Context, *sign.Options, string) ([]string, error)) {
	fake.tlogEntryUUIDsMutex.Lock()
	defer fake.tlogEntryUUIDsMutex.Unlock()
	fake.TlogEntryUUIDsStub = stub
}

func (fake *FakeImpl) TlogEntryUUIDsArgsForCall(i int) (context.Context, *sign.Options, string) {
	fake.tlogEntryUUIDsMutex.RLock()
	defer fake.tlogEntryUUIDsMutex.RUnlock()
	argsForCall := fake.tlogEntryUUIDsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) TlogEntryUUIDsArgs() []FakeImplTlogEntryUUIDsArgs {
	fake.tlogEntryUUIDsMutex.RLock()
	defer fake.tlogEntryUUIDsMutex.RUnlock()
	args := make([]FakeImplTlogEntryUUIDsArgs, len(fake.tlogEntryUUIDsArgsForCall))
	copy(args, fake.tlogEntryUUIDsArgsForCall)
	return args
}

func (fake *FakeImpl) TlogEntryUUIDsReturns(result1 []string, result2 error) {
	fake.tlogEntryUUIDsMutex.Lock()
	defer fake.tlogEntryUUIDsMutex.Unlock()
	fake.TlogEntryUUIDsStub = nil
	fake.tlogEntryUUIDsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) TlogEntryUUIDsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.tlogEntryUUIDsMutex.Lock()
	defer fake.tlogEntryUUIDsMutex.Unlock()
	fake.TlogEntryUUIDsStub = nil
	if fake.tlogEntryUUIDsReturnsOnCall == nil {
		fake.tlogEntryUUIDsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.tlogEntryUUIDsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) TokenFromProviders(arg1 context.Context, arg2 *logrus.Logger) (string, error) {
	fake.tokenFromProvidersMutex.Lock()
	ret, specificReturn := fake.tokenFromProvidersReturnsOnCall[len(fake.tokenFromProvidersArgsForCall)]
	fake.tokenFromProvidersArgsForCall = append(fake.tokenFromProvidersArgsForCall, FakeImplTokenFromProvidersArgs{arg1, arg2})
	stub := fake.TokenFromProvidersStub
	fakeReturns := fake.tokenFromProvidersReturns
	fake.recordInvocation("TokenFromProviders", []interface{}{arg1, arg2})
	fake.tokenFromProvidersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) TokenFromProvidersCallCount() int {
	fake.tokenFromProvidersMutex.RLock()
	defer fake.tokenFromProvidersMutex.RUnlock()
	return len(fake.tokenFromProvidersArgsForCall)
}

func (fake *FakeImpl) TokenFromProvidersCalls(stub func(context.Context, *logrus.Logger) (string, error)) {
	fake.tokenFromProvidersMutex.Lock()
	defer fake.tokenFromProvidersMutex.Unlock()
	fake.TokenFromProvidersStub = stub
}

func (fake *FakeImpl) TokenFromProvidersArgsForCall(i int) (context.Context, *logrus.Logger) {
	fake.tokenFromProvidersMutex.RLock()
	defer fake.tokenFromProvidersMutex.RUnlock()
	argsForCall := fake.tokenFromProvidersArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakeImpl) TokenFromProvidersArgs() []FakeImplTokenFromProvidersArgs {
	fake.tokenFromProvidersMutex.RLock()
	defer fake.tokenFromProvidersMutex.RUnlock()
	args := make([]FakeImplTokenFromProvidersArgs, len(fake.tokenFromProvidersArgsForCall))
	copy(args, fake.tokenFromProvidersArgsForCall)
	return args
}

func (fake *FakeImpl) TokenFromProvidersReturns(result1 string, result2 error) {
	fake.tokenFromProvidersMutex.Lock()
	defer fake.tokenFromProvidersMutex.Unlock()
	fake.TokenFromProvidersStub = nil
	fake.tokenFromProvidersReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) TokenFromProvidersReturnsOnCall(i int, result1 string, result2 error) {
	fake.tokenFromProvidersMutex.Lock()
	defer fake.tokenFromProvidersMutex.Unlock()
	fake.TokenFromProvidersStub = nil
	if fake.tokenFromProvidersReturnsOnCall == nil {
		fake.tokenFromProvidersReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.tokenFromProvidersReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) VerifyFileInternal(arg1 context.Context, arg2 *sign.Options, arg3 string, arg4 bool) error {
	fake.verifyFileInternalMutex.Lock()
	ret, specificReturn := fake.verifyFileInternalReturnsOnCall[len(fake.verifyFileInternalArgsForCall)]
	fake.verifyFileInternalArgsForCall = append(fake.verifyFileInternalArgsForCall, FakeImplVerifyFileInternalArgs{arg1, arg2, arg3, arg4})
	stub := fake.VerifyFileInternalStub
	fakeReturns := fake.verifyFileInternalReturns
	fake.recordInvocation("VerifyFileInternal", []interface{}{arg1, arg2, arg3, arg4})
	fake.verifyFileInternalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImpl) VerifyFileInternalCallCount() int {
	fake.verifyFileInternalMutex.RLock()
	defer fake.verifyFileInternalMutex.RUnlock()
	return len(fake.verifyFileInternalArgsForCall)
}

func (fake *FakeImpl) VerifyFileInternalCalls(stub func(context.Context, *sign.Options, string, bool) error) {
	fake.verifyFileInternalMutex.Lock()
	defer fake.verifyFileInternalMutex.Unlock()
	fake.VerifyFileInternalStub = stub
}

func (fake *FakeImpl) VerifyFileInternalArgsForCall(i int) (context.Context, *sign.Options, string, bool) {
	fake.verifyFileInternalMutex.RLock()
	defer fake.verifyFileInternalMutex.RUnlock()
	argsForCall := fake.verifyFileInternalArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeImpl) VerifyFileInternalArgs() []FakeImplVerifyFileInternalArgs {
	fake.verifyFileInternalMutex.RLock()
	defer fake.verifyFileInternalMutex.RUnlock()
	args := make([]FakeImplVerifyFileInternalArgs, len(fake.verifyFileInternalArgsForCall))
	copy(args, fake.verifyFileInternalArgsForCall)
	return args
}

func (fake *FakeImpl) VerifyFileInternalReturns(result1 error) {
	fake.verifyFileInternalMutex.Lock()
	defer fake.verifyFileInternalMutex.Unlock()
	fake.VerifyFileInternalStub = nil
	fake.verifyFileInternalReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) VerifyFileInternalReturnsOnCall(i int, result1 error) {
	fake.verifyFileInternalMutex.Lock()
	defer fake.verifyFileInternalMutex.Unlock()
	fake.VerifyFileInternalStub = nil
	if fake.verifyFileInternalReturnsOnCall == nil {
		fake.verifyFileInternalReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyFileInternalReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImpl) VerifyImageInternal(arg1 context.Context, arg2 *sign.Options, arg3 string) (string, error) {
	fake.verifyImageInternalMutex.Lock()
	ret, specificReturn := fake.verifyImageInternalReturnsOnCall[len(fake.verifyImageInternalArgsForCall)]
	fake.verifyImageInternalArgsForCall = append(fake.verifyImageInternalArgsForCall, FakeImplVerifyImageInternalArgs{arg1, arg2, arg3})
	stub := fake.VerifyImageInternalStub
	fakeReturns := fake.verifyImageInternalReturns
	fake.recordInvocation("VerifyImageInternal", []interface{}{arg1, arg2, arg3})
	fake.verifyImageInternalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImpl) VerifyImageInternalCallCount() int {
	fake.verifyImageInternalMutex.RLock()
	defer fake.verifyImageInternalMutex.RUnlock()
	return len(fake.verifyImageInternalArgsForCall)
}

func (fake *FakeImpl) VerifyImageInternalCalls(stub func(context.Context, *sign.Options, string) (string, error)) {
	fake.verifyImageInternalMutex.Lock()
	defer fake.verifyImageInternalMutex.Unlock()
	fake.VerifyImageInternalStub = stub
}

func (fake *FakeImpl) VerifyImageInternalArgsForCall(i int) (context.Context, *sign.Options, string) {
	fake.verifyImageInternalMutex.RLock()
	defer fake.verifyImageInternalMutex.RUnlock()
	argsForCall := fake.verifyImageInternalArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeImpl) VerifyImageInternalArgs() []FakeImplVerifyImageInternalArgs {
	fake.verifyImageInternalMutex.RLock()
	defer fake.verifyImageInternalMutex.RUnlock()
	args := make([]FakeImplVerifyImageInternalArgs, len(fake.verifyImageInternalArgsForCall))
	copy(args, fake.verifyImageInternalArgsForCall)
	return args
}

func (fake *FakeImpl) VerifyImageInternalReturns(result1 string, result2 error) {
	fake.verifyImageInternalMutex.Lock()
	defer fake.verifyImageInternalMutex.Unlock()
	fake.VerifyImageInternalStub = nil
	fake.verifyImageInternalReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) VerifyImageInternalReturnsOnCall(i int, result1 string, result2 error) {
	fake.verifyImageInternalMutex.Lock()
	defer fake.verifyImageInternalMutex.Unlock()
	fake.VerifyImageInternalStub = nil
	if fake.verifyImageInternalReturnsOnCall == nil {
		fake.verifyImageInternalReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.verifyImageInternalReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImpl) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImpl) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeImpl) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
